--blank-lines-after-procedures
-i4
--braces-after-struct-decl-line
--braces-after-func-def-line
--braces-on-if-line
--cuddle-else
--line-length 100
-bfde -bfda
--no-tabs
--format-all-comments
--swallow-optional-blank-lines
--preserve-mtime
