name: Build examples

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - $default-branch

env:
  BUILD_DIR: build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: examples-atmega32

    container:
      image: lukaszkostka/avr:alpine_3.16
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake
          --preset ${{ matrix.preset }}
          .

      - name: Build
        run: >
          cmake 
          --build ${{ env.BUILD_DIR }}
