name: Build examples

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - $default-branch

env:
  BUILD_DIR: build

defaults:
  run:
    working-directory: examples

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mcu: atmega32
            preset: release-avr
            cxx: avr-g++

          - mcu: atmega328
            preset: release-avr
            cxx: avr-g++

    container:
      image: lukaszkostka/avr:alpine_3.16
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        env:
          MCU: ${{ matrix.mcu }}
          CXX: ${{ matrix.cxx }}
        run: >
          cmake
          --preset ${{ matrix.preset }}
          .

      - name: Build
        run: >
          cmake 
          --build ${{ env.BUILD_DIR }}
