name: Unit tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - $default-branch

env:
  BUILD_DIR: build

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: lukaszkostka/avr:alpine_3.16
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake
          --preset unit-tests
          .

      - name: Build
        run: >
          cmake 
          --build ${{ env.BUILD_DIR }}

      - name: Run tests
        run: ${{ env.BUILD_DIR }}/tests/unit_tests
